# Generated by Django 3.0.7 on 2020-07-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('contenido', models.CharField(max_length=50, verbose_name='Contenido')),
                ('imagem', models.ImageField(upload_to='', verbose_name='Imagem')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em:')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado em:')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
